version: 2.1
orbs:
  sfdx: circleci/salesforce-sfdx@2.2.0
jobs:
  install_authenticate:
    executor: sfdx/default
    # docker:
    #   - image: cimg/node:14.5
    steps:
      - checkout
      - sfdx/install
      # - sfdx/auth:
      #     defaultusername: julien.masson-ratel@brp.com.devcoe
      #     instanceUrl: https://brp--devcoe.sandbox.my.salesforce.com/


#       sfdx auth:jwt:grant --clientid $SFDX_CONSUMER_KEY \
# --jwtkeyfile ./server.key --username cicd@brp.com.devcoe  \
# --setdefaultdevhubusername --setalias ${CIRCLE_PROJECT_REPONAME}-${CIRCLE_BRANCH}
      - run:
          name: Other auth not working?
          command: sfdx auth:jwt:grant --clientid 3MVG98EE59.VIHmxTt2OJwaVPnFtHSOuBwltawrlN5MDs2dK2XTJMlqapT1.0sL6DPYySEb7FHmfTJXD4JLrC --jwtkeyfile ./server.key --username julien.masson-ratel@brp.com.devcoe --instanceurl https://brp--devcoe.sandbox.my.salesforce.com/ --setdefaultdevhubusername --setalias COE
      - run:
          name: Run your SFDX commands here
          command: |
            echo "You now have access to the sfdx cli and may execute commands against it. https://developer.salesforce.com/docs/atlas.en-us.sfdx_cli_reference.meta/sfdx_cli_reference/cli_reference.htm"
      - run:
          name: Check Auth List
          command: sfdx force:auth:list
workflows:
  basic-test:
    jobs:
      - install_authenticate