version: 2.1
orbs:
  sfdx: circleci/salesforce-sfdx@2.2.0
  python: circleci/python@2.1.1

jobs:
  set_package:
    executor: python/default
    steps:
      - checkout
      # - python/install-packages:
      #     app-dir: .
      #     args: lxml
      #     pkg-manager: pip
      - run:
          name: Find folder and package.xml based on branch name
          command: |
            ls -a
            python ./scripts/cicd/find_folder.py ${CIRCLE_BRANCH} > ./package.txt
            cat ./package.txt
            export PACKAGE=$(cat ./package.txt)
            python ./scripts/cicd/parse_package_for_tests.py $PACKAGE > ./tests.txt
            cat ./tests.txt
            export TEST_CLASSES=$(cat ./tests.txt)
            echo ${TEST_CLASSES}
            echo << pipeline.git.branch >>
            echo << pipeline.trigger_source >>
            echo $CIRCLE_OIDC_TOKEN >> ./secret.txt
            cat ./secret.txt
            echo $CIRCLE_OIDC_TOKEN_V2
            printenv

  install_authenticate:
    executor: sfdx/default
    # docker:
    #   - image: cimg/node:14.5
    steps:
      - checkout
      - sfdx/install
      - sfdx/auth:
          defaultusername: ${SFDX_USERNAME}
          instanceUrl: https://test.salesforce.com
      - run:
          name: Run your SFDX commands here
          command: |
            echo "You now have access to the sfdx cli and may execute commands against it. https://developer.salesforce.com/docs/atlas.en-us.sfdx_cli_reference.meta/sfdx_cli_reference/cli_reference.htm"
            sfdx --version
            echo ${MY_ENV_VAR}
            echo ${PROJECT_ENV_VAR}
            echo ${CONTEXT_ENV_VAR}
            echo ${SFDX_USERNAME}
            printenv
      - run:
          name: Check Auth List
          command: sfdx force:auth:list
      - run:
          name: Deploy check only demo
          command: |
            export JOB_ID=$(sfdx force:source:deploy -x ./manifest/demo-branch/package2.xml -l RunSpecifiedTests -r FooTest -c -u ${SFDX_USERNAME} -w 0)
            echo ${JOB_ID}
            sleep 30
            sfdx force:source:deploy:report -i ${JOB_ID}

workflows:
  basic-test:
    jobs:
      - set_package
      - install_authenticate:
          context:
            - dev-coe
            - org-global